server:
  port: 8060
spring:
  application:
    name: order-seata
  datasource:
    url: jdbc:mysql://192.168.84.128:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 192.168.84.128:8848
      discovery:
        username: nacos
        password: nacos
        group: SEATA_GROUP

mybatis:
  mapper-locations: classpath*:com/academy/order/**/xml/*Mapper.xml
#  mapper-locations: classpath:mapper/OrderMapper.xml
#  mapper-locations: classpath:com.academy.order.mapper/OrderMapper.xml
  typeAliasesPackage: com.academy.order.entity
  configuration:
    mapUnderscoreToCamelCase: true
seata:
  config:
    type: nacos
    nacos:
      server-addr: 192.168.84.128:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.84.128:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username: nacos
      password: nacos
    #    nacos:
#      application: seata-server
#      server-addr: 192.168.84.128:8848
#      group: SEATA_GROUP
#      namespace:
#      cluster: default
#      username:
#      password:
    ##if use MSE Nacos with auth, mutex with username/password attribute
    #access-key: ""
    #secret-key: ""
  tx-service-group: xiamen
  service:
    grouplist:
      seata-server: 192.168.84.128:8091

